name:                better-lib
version:             0.1.0.0
github:              "foxfriends/better"
license:             BSD3
author:              "Cameron Eldridge"
maintainer:          "cameldridge+git@gmail.com"
copyright:           "2019 Cameron Eldridge"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/foxfriends/better#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2.3.1 && < 1.3
- containers >= 0.6.0.1 && < 0.7
- directory >= 1.3.3.0 && < 1.4
- filepath >= 1.4.2.1 && < 1.5
- optparse-applicative >= 0.14.3.0 && < 0.15
- terminal-size >= 0.3.2.1 && < 0.4
- tomland >= 1.1.0 && < 1.2
- transformers >= 0.5.6 && < 0.6

library:
  source-dirs: src

executables:
  better:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - better-lib

tests:
  better-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - better-lib
